#BOARD

#- lays out game grid (4x10?)
#- assign colors to letters
#- generates four-element sequence
#auto-generated by computer BECAUSE THE PLAYER WOULDN'T CHOOSE THE SECRET SEQUENCE THEY'LL BE GUESSING, JESUSFUCKINGCHRIST
#- stores secret sequence
#- start the game timer
#- accepts user input (4 letter guesses)
#- compare user input/guess to secret sequence
#do I need a separate guess checker for this?
#- way to accept correct guess
#- way to accept incorrect guess
#- check if there are guesses left
#- count guesses
#- end game if secret sequence is guessed
#- stop the game timer
